### ISSUE TITLE
Changing Job Time While Running

### ISSUE THREAD

**Issue by eranShalev** [yuvaldolev/Jobs#1]
It would be extremely helpful if I could change Job time while running

**Comment by yuvaldolev** [comment]
OK, will be added soon, thanks! 🙂

**Comment by eranShalev** [comment]
Nice bro very cool man

בתאריך יום ב׳, 4 בפבר׳ 2019, 17:08, מאת yuvaldolev <notifications@github.com

**Comment by yuvaldolev** [comment]
This has been implemented! 😄
